language: python
python:
   - "2.7"
before_install:
   # Get the tag if it wasn't provided. Travis doesn't provide this if it isn't a tagged build.
   - if [ -z $TRAVIS_TAG ]; then TRAVIS_TAG=`git tag --contains` ; fi
   - echo $TRAVIS_TAG
   # Move out of git directory to build root.
   - deactivate
   - cd ../..
   - pwd
install:
   # Download and configure conda.
   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
   - bash miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - conda config --set always_yes yes
   - conda config --add channels http://conda.binstar.org/jakirkham
   - source activate root
   # Install basic conda dependencies.
   - conda update conda
   - conda install conda-build
   # Setup environment for nanshe and install it with all dependencies.
   - conda create -n sphinxenv python=$TRAVIS_PYTHON_VERSION
   - cd $TRAVIS_REPO_SLUG
script:
   # Build and install the Sphinx conda package for nanshe.
   - conda pipbuild sphinx
   - source activate sphinxenv
   - conda install --use-local sphinx
# Use container format for TravisCI to avoid termination due to insufficient resources.
sudo: false
